#!/usr/bin/env python
# 2014-07-14/DN: Copies dotfiles to whereever they belong
# Should probably be a bash script but I'm learning Python.

# 2015-05-02/DN: since I used ~ and both branches do the same thing I'm not sure 
# what the point of this was.

import os
import socket
HOST = socket.gethostname()

if HOST.startswith("RSG", 0, 3) :
  #print "work laptop"
  os.system("cp -v ~/github/dotfiles/alias ~/.alias")
  os.system("cp -v ~/github/dotfiles/profile ~/.bash_profile")
  os.system("cp -v ~/github/dotfiles/bashrc ~/.bashrc")
  os.system("cp -v ~/github/dotfiles/inputrc ~/.inputrc")
  os.system("cp -v ~/github/dotfiles/screenrc ~/.screenrc")
else :
  #print "not work laptop"
  os.system("cp -v ~/github/dotfiles/alias ~/.alias")
  os.system("cp -v ~/github/dotfiles/profile ~/.bash_profile")
  os.system("cp -v ~/github/dotfiles/bashrc  ~/.bashrc")
  os.system("cp -v ~/github/dotfiles/inputrc ~/.inputrc")
  os.system("cp -v ~/github/dotfiles/screenrc ~/.screenrc")



# TODO: 
# 2014-07-15: use a variable for the source dir 
# 2014-07-15: figure out how to copy files with python
